filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/fastapi/json*
  tags: ["UGC_2"]
  fields:
    log_type: "fastapi"

  processors:
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      max_depth: 2
      target: ""
      overwrite_keys: true
      add_error_key: false

- type: filestream
  enabled: true
  paths:
    - /var/log/fastapi/text*
  tags: ["UGC_2"]
  fields:
    log_type: "fastapi"

- type: filestream
  enabled: true
  paths:
    - /var/log/nginx/*
  tags: ["UGC_2"]
  fields:
    log_type: "nginx"

  processors:
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      max_depth: 2
      target: ""
      overwrite_keys: true
      add_error_key: false

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
