filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/fastapi/*
  tags: ["UGC_2"]
  fields:
    log_type: "fastapi"

- type: filestream
  enabled: true
  paths:
    - /var/log/nginx/*
  tags: ["UGC_2"]
  fields:
    log_type: "nginx"

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
